//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTiendaElectronica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totales
    {
        public int ID_insercion { get; set; }
        public int Codigo { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Almacen Almacen { get; set; }
    }
}
